//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIP_Translator
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string TranslateSource { get; set; }
        public string TranslateTarget { get; set; }
        public System.DateTime Date { get; set; }
        public int IdLangIn { get; set; }
        public int IdLangOut { get; set; }
    
        public virtual Langs Langs { get; set; }
        public virtual Langs Langs1 { get; set; }
    }
}
